PeliculasElasticBeanstalk/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PeliculasElasticBeanstalk.Models
{
    [Table("peliculas")]
    public class Pelicula
    {
        [Key]
        [Column("id")]
        public int IdPelicula { get; set; }
        [Column("titulo")]
        public String Titulo { get; set; }
        [Column("genero")]
        public String Genero { get; set; }
        [Column("director")]
        public String Director { get; set; }
    }
}

PeliculasElasticBeanstalk/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PeliculasElasticBeanstalk.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PeliculasElasticBeanstalk.Controllers
{
    public class HomeController: Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

PeliculasElasticBeanstalk/Controllers/PeliculasController.cs
using Microsoft.AspNetCore.Mvc;
using PeliculasElasticBeanstalk.Models;
using PeliculasElasticBeanstalk.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeliculasElasticBeanstalk.Controllers
{
    public class PeliculasController: Controller
    {
        RepositoryPeliculas Repo;

        public PeliculasController(RepositoryPeliculas repo)
        {
            this.Repo = repo;
        }

        public IActionResult Index()
        {
            return View(this.Repo.GetPeliculas());
        }

        public IActionResult Details(int id)
        {
            return View(this.Repo.FindPelicula(id));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(int idpelicula, String titulo, String genero, String director)
        {
            this.Repo.CreatePelicula(idpelicula, titulo, genero, director);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            return View(this.Repo.FindPelicula(id));
        }

        [HttpPost]
        public IActionResult Edit(int id, String titulo, String genero, String director)
        {
            this.Repo.EditPelicula(id, titulo, genero, director);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            this.Repo.DeletePelicula(id);
            return RedirectToAction("Index");
        }
    }
}

PeliculasElasticBeanstalk/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PeliculasElasticBeanstalk/Views/Peliculas/Create.cshtml
@model Pelicula

<h1>Crear nueva película</h1>

<h4>Pelicula</h4>
<hr />
<form method="post">
    <label>Id</label>
    <input type="number" name="idpelicula" class="form-control" />
    <label>Título</label>
    <input type="text" name="titulo" class="form-control" />
    <label>Género</label>
    <input type="text" name="genero" class="form-control" />
    <label>Director</label>
    <input type="text" name="director" class="form-control" /><br />
    <button type="submit" class="btn btn-success">Crear película</button>
</form>
<br />
<a asp-action="Index" asp-controller="Peliculas">Volver a lista</a>

PeliculasElasticBeanstalk/Views/Peliculas/Details.cshtml
@model Pelicula

<h1 style="color: orange">Detalles de película</h1>
<br />
<ul class="list-group">
    <li class="list-group-item"><b>Id de película</b>: @Model.IdPelicula</li>
    <li class="list-group-item"><b>Título:</b> @Model.Titulo</li>
    <li class="list-group-item"><b>Género:</b> @Model.Genero</li>
    <li class="list-group-item"><b>Director:</b> @Model.Director</li>
</ul>
<br />
<a asp-action="Index" asp-controller="Peliculas" class="btn btn-info">Volver a lista</a>

PeliculasElasticBeanstalk/Views/Peliculas/Edit.cshtml
@model Pelicula

<h1>Editar película</h1>

<h4>Pelicula</h4>
<hr />
<form method="post">
    <label>Id</label>
    <input type="number" name="idpelicula" value="@Model.IdPelicula" class="form-control" readonly />
    <label>Título</label>
    <input type="text" name="titulo" value="@Model.Titulo" class="form-control" />
    <label>Género</label>
    <input type="text" name="genero" value="@Model.Genero" class="form-control" />
    <label>Director</label>
    <input type="text" name="director" value="@Model.Director" class="form-control" /><br />
    <button type="submit" class="btn btn-success">Editar película</button>
</form>
<br />
<a asp-action="Index" asp-controller="Peliculas">Volver a lista</a>

PeliculasElasticBeanstalk/Views/Peliculas/Index.cshtml
@model List<Pelicula>

<h1 style="color: limegreen">Index de PELÍCULAS</h1>
<br />
<a asp-action="Create" asp-controller="Peliculas" class="btn btn-primary">Crear NUEVA película</a>
<br /><br />
<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Pelicula p in Model)
        {
            <tr>
                <td>@p.Titulo</td>
                <td>
                    <a asp-action="Edit" asp-controller="Peliculas"
                       asp-route-id="@p.IdPelicula" class="btn btn-info">Editar</a> | 
                    <a asp-action="Details" asp-controller="Peliculas"
                       asp-route-id="@p.IdPelicula" class="btn btn-warning">Detalles</a> | 
                    <a asp-action="Delete" asp-controller="Peliculas"
                       asp-route-id="@p.IdPelicula" class="btn btn-danger">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PeliculasElasticBeanstalk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeliculasElasticBeanstalk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeliculasElasticBeanstalk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" asp-controller="Peliculas" asp-action="Index">Películas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PeliculasElasticBeanstalk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>